#![forbid(unsafe_code)]
//! Cross-backend interoperability tests for uselesskey.
//!
//! Verifies that keys generated by uselesskey work correctly across multiple
//! cryptographic backends (ring and RustCrypto crates such as p256, ed25519-dalek, rsa).
// Cross-backend interoperability tests — see tests/ directory.
